##################### Exercise 2 Makefile #######################
# AUTHOR:   Samuel Terra Vieira                                 #
# ADDRESS:  Universidade Federal de Lavras                      #
# DATE:     09/2019                                             #
#################################################################

# The project name
PROJECT_NAME=exercise02

include ../../Makefile.mk

CC_EXTRA_LIB_FLAGS=-lpthread
