##################### Exercise 1 Makefile #######################
# AUTHOR:   Samuel Terra Vieira                                 #
# ADDRESS:  Universidade Federal de Lavras                      #
# DATE:     09/2019                                             #
#################################################################

# The project name
PROJECT_NAME=exercise01

include ../../Makefile.mk