##################### Exercise 1 Makefile #######################
# AUTHOR:   Samuel Terra Vieira                                 #
# ADDRESS:  Universidade Federal de Lavras                      #
# DATE:     23/09/2019                                          #
#################################################################

# The project name
PROJECT_NAME=exercise04

include ../../Makefile.mk

CC_EXTRA_LIB_FLAGS=-lpthread